from os import name
from typing import List, Optional, Dict
from enum import Enum
from .Items import ItemData, items, events, assists, aptitudes, costumes, currencies,\
   equipments, quests, keys, materials, passives, skills, spirits, stats, tips
from dataclasses import dataclass


class LocationGroup(Enum):
    """
    Used to group locations
    """

    Boss = 0
    Event = 1
    Interactable = 2


@dataclass
class LocationData:
    name: str
    address: Optional[int] = None
    key: Optional[str] = None
    content: Optional[ItemData] = None
    group: Optional[LocationGroup] = None

locations_data = [
    ("Center 1 - Gilroy",                                 "Center_001_Zone_001.EVT_ev_s_e6050_Master_Defeat",          aptitudes["SP"]),
    ("Center 1 - Origin Gem Core",                        "Center_001_Zone_001.BP_Interactable_AddItem_C_1",           materials["parts_lv6_a"]),
    ("Center 1 - Huginn",                                 "Center_001_Zone_001.EVT_ev_n_Levy_Treasure3_002",           spirits["s5080_hawk"]),
    ("Center 2 - Mantle of Milius",                       "Center_001_Zone_002.EVT_ev_n_Center_costume_001",           costumes["p0030"]),
    ("Center 3 - Charmed Fragment",                       "Center_001_Zone_003.BP_Breakable_SpawnItem_Pod_01_C_1",     stats["hp_up_s"]),
    ("Center 4 - Faintly Glowing Aegis Curio",            "Center_001_Zone_004.EVT_ev_n_Levy_Treasure6_002",           quests["quest_amulet"]),
    ("Crossroad 2 - Charmed Fragment",                    "Crossroad_001_Zone_002.BP_Interactable_AddItem_C_1",        stats["hp_up_s"]),
    ("Crossroad 3 - Subterranean Laborer's Code",         "Crossroad_001_Zone_003.BP_Interactable_AddItem_C_1",        tips["tip_workerscode_01"]),
    ("Crossroad 5 - Dodge",                               "Crossroad_001_Zone_005.EVT_ev_s_0050_LevyMeeting.1",        aptitudes["dodge"]),
    ("Crossroad 5 - Aerial Jump",                         "Crossroad_001_Zone_005.EVT_ev_s_0050_LevyMeeting",          aptitudes["double_jump"]),
    ("Estate 2 - Lorna 1",                                "Estate_001_Zone_002.EVT_ev_s_n5040_Maiden_Defeat",          spirits["s5040_maiden"]),
    ("Estate 2 - Lorna 2",                                "Estate_001_Zone_002.EVT_ev_s_n5040_Maiden_Defeat.1",        keys["key_higher_a"]),
    ("Estate 3 - Special Alloy Core",                     "Estate_001_Zone_003.BP_Interactable_AddItem_C_0",           materials["parts_lv5_a"]),
    ("Estate 4 - Abelia's Bracelet",                      "Estate_001_Zone_004.BP_Interactable_AddItem_C_0",           equipments["armor_014"]),
    ("Estate 5 - Scrap",                                  "Estate_001_Zone_005.BP_Interactable_AddItem_C_0",           currencies["rare"]),
    ("Estate 6 - Frost Confidential Records 2",           "Estate_001_Zone_006.BP_Interactable_AddItem_C_0",           tips["tip_frostsrecord_02"]),
    ("Estate 7 - Charmed Fragment",                       "Estate_001_Zone_007.BP_Interactable_AddItem_C_0",           stats["hp_up_s"]),
    ("Estate 7 - Materials",                              "Estate_001_Zone_007.BP_Interactable_AddItem_C_1",           currencies["Default"]),
    ("Estate 7 - Levy",                                   "Estate_001_Zone_007.BP_Trigger_Event_LevyTreasure_C_1",     quests["quest_artifact"]),
    ("Estate 8 - Scrap",                                  "Estate_001_Zone_008.BP_Interactable_AddItem_C_1",           currencies["rare"]),
    ("Estate 10 - Grimoire",                              "Estate_001_Zone_010.BP_Interactable_TreasureBox_C_1",       stats["shop_line_up"]),
    ("Estate 11 - Special Alloy Core",                    "Estate_001_Zone_011.BP_Interactable_AddItem_C_0",           materials["parts_lv5_a"]),
    ("Estate 12 - Frost Confidential Records 1",          "Estate_001_Zone_012.BP_Interactable_AddItem_C_0",           tips["tip_frostsrecord_01"]),
    ("Factory 1 - Special Alloy Core",                    "Factory_001_Zone_001.BP_Interactable_AddItem_C_0",          materials["parts_lv5_a"]),
    ("Factory 1 - Mysterious Glowing Can",                "Factory_001_Zone_001.BP_Interactable_AddItem_C_1",          passives["stamina_damage_up_b_1"]),
    ("Factory 2 - Worker's Surveillance Records",         "Factory_001_Zone_002.BP_Interactable_AddItem_C_0",          tips["tip_surveillancerecord_01"]),
    ("Factory 5 - Scrap",                                 "Factory_001_Zone_005.BP_Interactable_AddItem_C_0",          currencies["rare"]),
    ("Factory 6 - Labourer's Tag",                        "Factory_001_Zone_006.BP_Interactable_TreasureBox_C_0",      passives["damage_cut_debuff_down_1"]),
    ("Factory 7 - Factory Management Records",            "Factory_001_Zone_007.BP_Interactable_AddItem_C_0",          tips["tip_administrationrecord_01"]),
    ("Factory 8 - Scrap",                                 "Factory_001_Zone_008.BP_Interactable_AddItem_C_1",          currencies["rare"]),
    ("Factory 9 - Charmed Fragment",                      "Factory_001_Zone_009.BP_Interactable_AddItem_C_0",          stats["hp_up_s"]),
    ("Factory 10 - Velnest",                              "Factory_001_Zone_010.EVT_ev_s_e2030_Sector_Defeat",         materials["parts_lv5_b"]),
    ("Factory 12 - Scrap",                                "Factory_001_Zone_012.BP_Interactable_AddItem_C_1",          currencies["rare"]),
    ("Factory 12 - Cain's Ring",                          "Factory_001_Zone_012.BP_Interactable_TreasureBox_C_1",      passives["onattack_restorehp_damage_1"]),
    ("Factory 13 - Charmed Fragment",                     "Factory_001_Zone_013.BP_Interactable_AddItem_C_0",          stats["hp_up_s"]),
    ("Factory 14 - Grimoire",                             "Factory_001_Zone_014.BP_Interactable_TreasureBox_C_1",      stats["shop_line_up"]),
    ("Factory 15 - Charmed Fragment",                     "Factory_001_Zone_015.BP_Interactable_AddItem_C_0",          stats["hp_up_s"]),
    ("Factory 15 - Magic Vial",                           "Factory_001_Zone_015.BP_Interactable_AddItem_C_1",          stats["passive_slot_s"]),
    ("Factory 18 - Miner Enchancement Project",           "Factory_001_Zone_018.BP_Interactable_AddItem_C_1",          tips["tip_enhancementplan_01"]),
    ("Factory 18 - Garm's Ascent",                        "Factory_001_Zone_018.EVT_ev_s_5200_Pounder_Upgrade",        aptitudes["high_jump"]),
    ("Factory 19 - Scrap",                                "Factory_001_Zone_019.BP_Interactable_AddItem_C_1",          currencies["rare"]),
    ("Factory 19 - Levy",                                 "Factory_001_Zone_019.BP_Trigger_Event_LevyTreasure_C_0",    quests["quest_stone"]),
    ("Factory 21 - Document on the Empyrean Parasol",     "Factory_001_Zone_021.EVT_ev_s_0250_KeyFactory.1",           tips["tip_towerumbrella_01"]),
    ("Factory 21 - Milius Lord's Mark",                   "Factory_001_Zone_021.EVT_ev_s_0250_KeyFactory",             keys["key_higher_b"]),
    ("Forest 1 - Crimson Bangle",                         "Forest_001_Zone_001.BP_Interactable_AddItem_C_1",           equipments["armor_008"]),
    ("Forest 2 - Obsolete Core",                          "Forest_001_Zone_002.BP_Interactable_AddItem_C_1",           materials["parts_lv3_b"]),
    ("Forest 2 - Words Etched into Stone",                "Forest_001_Zone_002.BP_Interactable_AddTutorial_C_1",       tips["tip_tombstone_01"]),
    ("Forest 4 - Charmed Fragment",                       "Forest_001_Zone_004.BP_Interactable_AddItem_C_1",           stats["hp_up_s"]),
    ("Forest 7 - Chain Belt",                             "Forest_001_Zone_007.BP_Interactable_AddItem_C_1",           passives["damage_up_grounded_1"]),
    ("Forest 9 - Charmed Fragment",                       "Forest_001_Zone_009.BP_Interactable_AddItem_C_1",           stats["hp_up_s"]),
    ("Forest 9 - Materials",                              "Forest_001_Zone_009.BP_Interactable_AddItem_C_3",           currencies["Default"]),
    ("Forest 9 - Effigy",                                 "Forest_001_Zone_009.BP_Interactable_AddItem_C_5",           passives["damage_cut_minhp_1"]),
    ("Forest 10 - Charmed Fragment",                      "Forest_001_Zone_010.BP_Interactable_AddItem_C_1",           stats["hp_up_s"]),
    ("Forest 10 - Materials",                             "Forest_001_Zone_010.BP_Interactable_AddItem_C_2",           currencies["Default"]),
    ("Forest 11 - Magic Vial",                            "Forest_001_Zone_011.BP_Interactable_AddItem_C_1",           stats["passive_slot_s"]),
    ("Forest 19 - Beast Horn Ornanment",                  "Forest_001_Zone_019.BP_Interactable_AddItem_C_1",           passives["damage_cut_maxhp_1"]),
    ("Forest 20 - Spy's Letter",                          "Forest_001_Zone_020.BP_Interactable_AddItem_C_0",           tips["tip_secretletter_01"]),
    ("Forest 20 - Charmed Fragment",                      "Forest_001_Zone_020.BP_Interactable_AddItem_C_1",           stats["hp_up_s"]),
    ("Forest 20 - Grimoire",                              "Forest_001_Zone_020.BP_Interactable_TreasureBox_C_1",       stats["shop_line_up"]),
    ("Forest 23 - Materials",                             "Forest_001_Zone_023.BP_Interactable_AddItem_C_1",           currencies["Default"]),
    ("Forest 23 - Cassia's Grimoire",                     "Forest_001_Zone_023.BP_Interactable_AddItem_C_3",           tips["tip_cassiabook_01"]),
    ("Forest 23 - Incomplete Gear",                       "Forest_001_Zone_023.EVT_ev_n_Levy_Treasure2_002",           passives["reduce_gravity"]),
    ("Forest 23 - Hati's Charge",                         "Forest_001_Zone_023.EVT_ev_s_5210_Fenris_Upgrade",          aptitudes["dash_charge"]),
    ("Garden 1 - Charmed Fragment 1",                     "Garden_001_Zone_001.BP_Interactable_AddItem_C_1",           stats["hp_up_s"]),
    ("Garden 1 - Charmed Fragment 2",                     "Garden_001_Zone_001.BP_Interactable_AddItem_C_2",           stats["hp_up_s"]),
    ("Garden 1 - Materials",                              "Garden_001_Zone_001.BP_Interactable_AddItem_C_4",           currencies["Default"]),
    ("Garden 1 - Bloodstained Stuffed Toy",               "Garden_001_Zone_001.BP_Interactable_TreasureBox_C_1",       passives["damage_cut_debuffed_1"]),
    ("Garden 2 - Sorcerer's Gauntlet",                    "Garden_001_Zone_002.BP_Interactable_TreasureBox_C_1",       passives["debuff_damage_up_b_1"]),
    ("Garden 2 - Chiron",                                 "Garden_001_Zone_002.BP_Interactable_TreasureBox_C_3",       assists["assist_009"]),
    ("Garden 3 - Grimoire",                               "Garden_001_Zone_003.BP_Interactable_AddItem_C_1",           stats["shop_line_up"]),
    ("Garden 3 - Arcane Smith's Musings",                 "Garden_001_Zone_003.BP_Interactable_AddItem_C_2",           tips["tip_engineermemoirs_01"]),
    ("Garden 3 - Chronicles of Milius",                   "Garden_001_Zone_003.BP_Interactable_AddItem_C_3",           tips["tip_miliusbook_01"]),
    ("Garden 3 - Words on Land's End",                    "Garden_001_Zone_003.BP_Interactable_AddItem_C_4",           tips["tip_landend_01"]),
    ("Garden 3 - Battered Grimoire",                      "Garden_001_Zone_003.BP_Interactable_AddItem_C_5",           passives["damage_up_debuffed_1"]),
    ("Garden 5 - Magic Amplifier",                        "Garden_001_Zone_005.EVT_ev_s_0233_Researcher_002",          materials["parts_lv4_b"]),
    ("Garden 5 - Tripartite Magic Vial",                  "Garden_001_Zone_005.EVT_ev_n_Levy_Treasure5_002",           stats["passive_slot_l"]),
    ("Garden 6 - Magic Vial",                             "Garden_001_Zone_006.BP_Breakable_SpawnItem_Pod_01_C_1",     stats["passive_slot_s"]),
    ("Garden 6 - Materials",                              "Garden_001_Zone_006.BP_Interactable_AddItem_C_1",           currencies["Default"]),
    ("Garden 6 - Origin Gem Core",                        "Garden_001_Zone_006.BP_Interactable_AddItem_C_2",           materials["parts_lv6_a"]),
    ("Garden 6 - Unidentified Amplifier",                 "Garden_001_Zone_006.BP_Interactable_TreasureBox_C_1",       materials["parts_s5000_b"]),
    ("Garden 7 - Luiseach's Carapace",                    "Garden_001_Zone_007.BP_Interactable_AddItem_C_1",           equipments["shield_009"]),
    ("Garden 8 - Scrap",                                  "Garden_001_Zone_008.BP_Interactable_AddItem_C_1",           currencies["rare"]),
    ("Garden 11 - Luiseach",                              "Garden_001_Zone_011.EVT_ev_s_e5070_Witch_Defeat",           spirits["s5070_witch"]),
    ("Garden 14 - Charmed Fragment",                      "Garden_001_Zone_014.BP_Interactable_AddItem_C_1",           stats["hp_up_s"]),
    ("Kowloon 5 - Mother's Note",                         "Kowloon_001_Zone_005.BP_Interactable_AddItem_C_0",          tips["tip_mothersnote_01"]),
    ("Kowloon 8 - Chief Attuner's Ring",                  "Kowloon_001_Zone_008.BP_Interactable_AddItem_C_1",          passives["restore_sp_up_a_1"]),
    ("Kowloon 9 - Levy",                                  "Kowloon_001_Zone_009.BP_Trigger_Event_LevyTreasure_C_0",    quests["quest_bird"]),
    ("Kowloon 13 - Scrap",                                "Kowloon_001_Zone_013.BP_Interactable_AddItem_C_1",          currencies["rare"]),
    ("Kowloon 18 - Charmed Fragment",                     "Kowloon_001_Zone_018.BP_Interactable_AddItem_C_0",          stats["hp_up_s"]),
    ("Kowloon 21 - Magic Amplifier",                      "Kowloon_001_Zone_021.BP_Interactable_AddItem_C_1",          materials["parts_lv4_b"]),
    ("Kowloon 26 - Materials",                            "Kowloon_001_Zone_026.BP_Interactable_AddItem_C_0",          currencies["Default"]),
    ("Kowloon 28 - Arena Tower Demon Mask",               "Kowloon_001_Zone_028.BP_Interactable_AddItem_C_0",          passives["damage_up_skillcategory_defence_1"]),
    ("Kowloon 28 - Magic Amplifier",                      "Kowloon_001_Zone_028.BP_Interactable_AddItem_C_1",          materials["parts_lv4_b"]),
    ("Kowloon 29 - Scrap",                                "Kowloon_001_Zone_029.BP_Interactable_AddItem_C_0",          currencies["rare"]),
    ("Kowloon 31 - Grimoire",                             "Kowloon_001_Zone_031.BP_Interactable_TreasureBox_C_0",      stats["shop_line_up"]),
    ("Kowloon 32 - Arena Tower Flyer",                    "Kowloon_001_Zone_032.BP_Interactable_AddItem_C_0",          tips["tip_fightingtower_01"]),
    ("Kowloon 33 - Fugitive Researcher's Notes",          "Kowloon_001_Zone_033.BP_Interactable_AddItem_C_0",          tips["tip_researchersjournal_01"]),
    ("Kowloon 35 - Charmed Fragment",                     "Kowloon_001_Zone_035.BP_Interactable_AddItem_C_0",          stats["hp_up_s"]),
    ("Kowloon 36 - Magicite Hairpin",                     "Kowloon_001_Zone_036.BP_Interactable_AddItem_C_0",          passives["onkill_reduce_cooldowns_1"]),
    ("Kowloon 39 - Magic Vial",                           "Kowloon_001_Zone_039.BP_Interactable_AddItem_C_0",          stats["passive_slot_s"]),
    ("Kowloon 39 - Materials",                            "Kowloon_001_Zone_039.BP_Interactable_AddItem_C_1",          currencies["Default"]),
    ("Kowloon 39 - Spica",                                "Kowloon_001_Zone_039.BP_Interactable_TreasureBox_C_0",      assists["assist_006"]),
    ("Kowloon 47 - Charmed Fragment",                     "Kowloon_001_Zone_047.BP_Interactable_AddItem_C_0",          stats["hp_up_s"]),
    ("Kowloon 47 - Origin Gem Core",                      "Kowloon_001_Zone_047.BP_Interactable_AddItem_C_2",          materials["parts_lv6_a"]),
    ("Kowloon 51 - No.7",                                 "Kowloon_001_Zone_051.EVT_ev_s_e5050_Ronin_Defeat",          spirits["s5050_ronin"]),
    ("Labo 1 - Lilia's Diary",                            "Labo_001_Zone_001.BP_Interactable_AddItem_C_0",             tips["tip_liliasdiary_01"]),
    ("Labo 3 - Aggressor",                                "Labo_001_Zone_003.EVT_ev_s_e5003_Reaper_Defeat",            materials["parts_s5000_a"]),
    ("Labo 6 - Echo Device",                              "Labo_001_Zone_006.BP_Interactable_TreasureBox_C_0",         passives["damage_up_skillcategory_combo_1"]),
    ("Labo 7 - Materials",                                "Labo_001_Zone_007.BP_Interactable_AddItem_C_1",             currencies["Default"]),
    ("Labo 8 - Charmed Fragment",                         "Labo_001_Zone_008.BP_Interactable_AddItem_C_0",             stats["hp_up_s"]),
    ("Labo 9 - Charmed Fragment",                         "Labo_001_Zone_009.BP_Interactable_AddItem_C_0",             stats["hp_up_s"]),
    ("Labo 10 - Magic Vial",                              "Labo_001_Zone_010.BP_Interactable_TreasureBox_C_1",         stats["passive_slot_s"]),
    ("Labo 11 - Scrap",                                   "Labo_001_Zone_011.BP_Interactable_AddItem_C_0",             currencies["rare"]),
    ("Labo 17 - Crtystallised Fusion",                    "Labo_001_Zone_017.BP_Interactable_AddItem_C_0",             passives["damage_cut_sp_gauge_1"]),
    ("Labo 18 - Charmed Fragment",                        "Labo_001_Zone_018.BP_Interactable_AddItem_C_0",             stats["hp_up_s"]),
    ("Labo 18 - Priestess' Tears",                        "Labo_001_Zone_018.BP_Interactable_AddItem_C_2",             passives["damage_up_sp_gauge_1"]),
    ("Labo 19 - Scrap",                                   "Labo_001_Zone_019.BP_Interactable_AddItem_C_0",             currencies["rare"]),
    ("Labo 21 - Lar's Swift Flight",                      "Labo_001_Zone_021.EVT_ev_s_5230_Finder_Upgrade",            aptitudes["wall_charge"]),
    ("Labo 22 - Gilroy Examination Record",               "Labo_001_Zone_022.BP_Interactable_AddItem_C_0",             tips["tip_gilroyrecords_01"]),
    ("Labo 24 - Caladrius Records",                       "Labo_001_Zone_024.BP_Interactable_AddItem_C_0",             tips["tip_caladriusrecord_01"]),
    ("Labo 24 - Grimoire",                                "Labo_001_Zone_024.BP_Interactable_TreasureBox_C_0",         stats["shop_line_up"]),
    ("Labo 26 - Materials",                               "Labo_001_Zone_026.BP_Interactable_AddItem_C_0",             currencies["Default"]),
    ("Labo 27 - Origin Gem Core",                         "Labo_001_Zone_027.BP_Interactable_TreasureBox_C_1",         materials["parts_lv6_a"]),
    ("Mine 2 - Helix Crystal",                            "Mine_001_Zone_002.BP_Interactable_AddItem_C_1",             passives["onkill_restorehp_1"]),
    ("Mine 4 - Miner Unit",                               "Mine_001_Zone_004.EVT_ev_s_e0122_Wheeler_Defeat",           materials["parts_lv2_b"]),
    ("Mine 4 - Writing Etched Into the Wall",             "Mine_001_Zone_004.BP_Interactable_AddItem_C_1",             tips["tip_writingwall_01"]),
    ("Mine 5 - Charmed Fragment",                         "Mine_001_Zone_005.BP_Interactable_AddItem_C_1",             stats["hp_up_s"]),
    ("Mine 5 - Materials",                                "Mine_001_Zone_005.BP_Interactable_AddItem_C_2",             currencies["Default"]),
    ("Mine 5 - Magic Vial",                               "Mine_001_Zone_005.BP_Interactable_AddItem_C_3",             stats["passive_slot_s"]),
    ("Mine 6 - Materials",                                "Mine_001_Zone_006.BP_Interactable_AddItem_C_0",             currencies["Default"]),
    ("Mine 6 - Charmed Fragment",                         "Mine_001_Zone_006.BP_Interactable_AddItem_C_1",             stats["hp_up_s"]),
    ("Mine 8 - Unidentified Amplifier",                   "Mine_001_Zone_008.BP_Interactable_AddItem_C_0",             materials["parts_s5000_b"]),
    ("Mine 9 - Muninn",                                   "Mine_001_Zone_009.EVT_ev_s_0080_FrostAndOwl",               spirits["s5090_owl"]),
    ("Mine 11 - Tarnished Tag",                           "Mine_001_Zone_011.BP_Interactable_TreasureBox_C_1",         passives["damage_cut_physic_1"]),
    ("Mine 12 - Charmed Fragment",                        "Mine_001_Zone_012.BP_Interactable_AddItem_C_0",             stats["hp_up_s"]),
    ("Mine 13 - Materials",                               "Mine_001_Zone_013.BP_Interactable_AddItem_C_1",             currencies["Default"]),
    ("Mine 13 - Grimoire",                                "Mine_001_Zone_013.BP_Interactable_TreasureBox_C_1",         stats["shop_line_up"]),
    ("Mine 14 - Notification of Restricted Areas",        "Mine_001_Zone_014.BP_Interactable_AddItem_C_0",             tips["tip_tunerjournal_01"]),
    ("Mine 14 - Levy",                                    "Mine_001_Zone_014.BP_Trigger_Event_LevyTreasure_C_0",       quests["quest_board"]),
    ("Mine 17 - Garm",                                    "Mine_001_Zone_017.EVT_ev_s_e5200_Pounder_Defeat",           aptitudes["pile_attack"]),
    ("Paradise 1 - Charmed Fragment 1",                   "Paradise_001_Zone_001.BP_Interactable_AddItem_C_1",         stats["hp_up_s"]),
    ("Paradise 1 - Charmed Fragment 2",                   "Paradise_001_Zone_001.BP_Interactable_AddItem_C_2",         stats["hp_up_s"]),
    ("Paradise 2 - Declan's Records",                     "Paradise_001_Zone_002.BP_Interactable_AddItem_C_0",         tips["tip_degrandsrecord_01"]),
    ("Paradise 3 - Magic Vial",                           "Paradise_001_Zone_003.BP_Interactable_AddItem_C_0",         stats["passive_slot_s"]),
    ("Paradise 3 - Grimoire",                             "Paradise_001_Zone_003.BP_Interactable_TreasureBox_C_0",     stats["shop_line_up"]),
    ("Paradise 5 - Charmed Fragment",                     "Paradise_001_Zone_005.BP_Interactable_AddItem_C_0",         stats["hp_up_s"]),
    ("Paradise 8 - No.47",                                "Paradise_001_Zone_008.EVT_ev_s_e0289_Banshee_Defeat",       materials["parts_lv5_b"]),
    ("Paradise 11 - Bloodstained Diary",                  "Paradise_001_Zone_011.BP_Interactable_AddItem_C_0",         tips["tip_bloodstaineddiary_01"]),
    ("Paradise 12 - Declan's Ring",                       "Paradise_001_Zone_012.BP_Interactable_TreasureBox_C_0",     passives["onattack_restorehp_1"]),
    ("Paradise 19 - Scrap",                               "Paradise_001_Zone_019.BP_Interactable_AddItem_C_0",         currencies["rare"]),
    ("Paradise 19 - Materials",                           "Paradise_001_Zone_019.BP_Interactable_AddItem_C_1",         currencies["Default"]),
    ("Paradise 19 - Motley's Torrent",                    "Paradise_001_Zone_019.EVT_ev_s_5220_Wirer_Upgrade",         aptitudes["dash_charge_underwater"]),
    ("Paradise 21 - Materials",                           "Paradise_001_Zone_021.BP_Interactable_AddItem_C_0",         currencies["Default"]),
    ("Paradise 24 - Words Etched into Cell",              "Paradise_001_Zone_024.BP_Interactable_AddItem_C_0",         tips["tip_prisonwall_01"]),
    ("Paradise 26 - Declan's Binds",                      "Paradise_001_Zone_026.BP_Interactable_AddItem_C_0",         equipments["armor_015"]),
    ("Paradise 30 - Grand Sorcerer's Key",                "Paradise_001_Zone_030.EVT_ev_n_e0289_Banshee_KeyGet",       keys["key_owner"]),
    ("Paradise 32 - Unidentified Transformer",            "Paradise_001_Zone_032.BP_Interactable_AddItem_C_0",         materials["parts_s5000_c"]),
    ("Paradise 33 - Headless Gold Statue",                "Paradise_001_Zone_033.BP_Interactable_AddItem_C_0",         passives["onkill_drops_1"]),
    ("Paradise 34 - Cracked Magicite Dagger",             "Paradise_001_Zone_034.BP_Interactable_TreasureBox_C_1",     passives["damage_up_skillcategory_special_1"]),
    ("Quarry 1 - Survey Teams Notes",                     "Quarry_001_Zone_001.BP_Interactable_AddTutorial_C_0",       tips["tip_freeze_01"]),
    ("Quarry 2 - Charmed Fragment",                       "Quarry_001_Zone_002.BP_Interactable_AddItem_C_2",           stats["hp_up_s"]),
    ("Quarry 3 - Tattered Notice",                        "Quarry_001_Zone_003.BP_Interactable_AddItem_C_0",           tips["tip_raggedpastedown_01"]),
    ("Quarry 3 - Levy",                                   "Quarry_001_Zone_003.BP_Trigger_Event_LevyTreasure_C_0",     quests["quest_perfume"]),
    ("Quarry 4 - Materials",                              "Quarry_001_Zone_004.BP_Interactable_AddItem_C_1",           currencies["Default"]),
    ("Quarry 4 - Grimoire",                               "Quarry_001_Zone_004.BP_Interactable_TreasureBox_C_1",       stats["shop_line_up"]),
    ("Quarry 5 - Materials",                              "Quarry_001_Zone_005.BP_Interactable_AddItem_C_0",           currencies["Default"]),
    ("Quarry 7 - Survey Team Gauntlet",                   "Quarry_001_Zone_007.BP_Interactable_AddItem_C_1",           passives["debuff_damage_up_a_1"]),
    ("Quarry 10 - New Model Core",                        "Quarry_001_Zone_010.BP_Interactable_AddItem_C_1",           materials["parts_lv4_a"]),
    ("Quarry 11 - Materials",                             "Quarry_001_Zone_011.BP_Interactable_AddItem_C_0",           currencies["Default"]),
    ("Quarry 14 - Magic Vial",                            "Quarry_001_Zone_014.BP_Interactable_AddItem_C_1",           stats["passive_slot_s"]),
    ("Quarry 15 - Depths Survey Record",                  "Quarry_001_Zone_015.BP_Interactable_AddItem_C_1",           tips["tip_lowestrecord_01"]),
    ("Quarry 15 - Charmed Fragment",                      "Quarry_001_Zone_015.BP_Interactable_AddItem_C_3",           stats["hp_up_s"]),
    ("Quarry 15 - Krios",                                 "Quarry_001_Zone_015.BP_Interactable_TreasureBox_C_1",       assists["assist_001"]),
    ("Quarry 16 - Materials",                             "Quarry_001_Zone_016.BP_Interactable_AddItem_C_0",           currencies["Default"]),
    ("Quarry 17 - Materials",                             "Quarry_001_Zone_017.BP_Interactable_AddItem_C_0",           currencies["Default"]),
    ("Quarry 18 - Blighted Talisman",                     "Quarry_001_Zone_018.BP_Interactable_AddItem_C_1",           passives["stamina_damage_up_a_1"]),
    ("Quarry 21 - Unidentified Core",                     "Quarry_001_Zone_021.BP_Interactable_AddItem_C_1",           materials["parts_s5000_a"]),
    ("Quarry 21 - Jagged Crystal",                        "Quarry_001_Zone_021.BP_Interactable_AddItem_C_2",           passives["damage_up_minhp_1"]),
    ("Quarry 24 - Materials",                             "Quarry_001_Zone_024.BP_Interactable_AddItem_C_0",           currencies["Default"]),
    ("Quarry 31 - Lar's Grip",                            "Quarry_001_Zone_031.EVT_ev_s_n7043_Quarry_Tuner",           aptitudes["wall_grab"]),
    ("Roots 1 - Reibolg 2",                               "Roots_001_Zone_001.EVT_ev_s_e5012_RootsLancer_Defeat.1",    quests["quest_eye"]),
    ("Roots 1 - Reibolg 1",                               "Roots_001_Zone_001.EVT_ev_s_e5012_RootsLancer_Defeat",      spirits["s5010_lancer"]),
    ("Roots 2 - White Priestess' Attire",                 "Roots_001_Zone_002.EVT_ev_s_FinalRelic.1" ,                 costumes["p0050"]),
    ("Roots 2 - Lilia's Blighted Ring",                   "Roots_001_Zone_002.EVT_ev_s_FinalRelic",                    passives["ending_flag"]),
    ("Roots 5 - Stele of the Land of Origin",             "Roots_001_Zone_005.EVT_ev_n_Levy_Treasure6_001",            quests["quest_lithograph"]),
    ("Roots 6 - Charmed Fragment",                        "Roots_001_Zone_006.BP_Interactable_AddItem_C_1",            stats["hp_up_s"]),
    ("Roots 6 - Origin Gem Core",                         "Roots_001_Zone_006.BP_Interactable_AddItem_C_3",            materials["parts_lv6_a"]),
    ("Roots 8 - Charmed Ore",                             "Roots_001_Zone_008.BP_Interactable_AddItem_C_1",            stats["hp_up_l"]),
    ("Roots 9 - Materials",                               "Roots_001_Zone_009.BP_Interactable_TreasureBox_C_1",        currencies["Default"]),
    ("Roots 11 - Blighted Prophecy",                      "Roots_001_Zone_011.BP_Interactable_AddItem_C_1",            tips["tip_prophecybook_01"]),
    ("Roots 12 - Typhon",                                 "Roots_001_Zone_012.BP_Interactable_AddItem_C_1",            assists["assist_010"]),
    ("Roots 17 - Joran's Notes 1",                        "Roots_001_Zone_017.BP_Interactable_AddItem_C_1",            tips["tip_yoransdiary_01"]),
    ("Roots 18 - Joran's Notes 2",                        "Roots_001_Zone_018.BP_Interactable_AddItem_C_0",            tips["tip_yoransdiary_02"]),
    ("Roots 20 - Primordial Heirloom",                    "Roots_001_Zone_020.BP_Interactable_TreasureBox_C_0",        equipments["shield_008"]),
    ("Roots 22 - Abelia's Ring",                          "Roots_001_Zone_022.BP_Interactable_TreasureBox_C_1",        passives["onattack_instantkill_1"]),
    ("Roots 23 - Origin Gem Core",                        "Roots_001_Zone_023.BP_Interactable_AddItem_C_0",            materials["parts_lv6_a"]),
    ("Roots 27 - Ancient's Fury",                         "Roots_001_Zone_027.BP_Interactable_TreasureBox_C_0",        equipments["armor_020"]),
    ("Roots 28 - Origin Gem Core",                        "Roots_001_Zone_028.BP_Interactable_AddItem_C_0",            materials["parts_lv6_a"]),
    ("Roots 29 - Charmed Ore",                            "Roots_001_Zone_029.BP_Interactable_AddItem_C_0",            stats["hp_up_l"]),
    ("Roots 30 - Unidentified Amplifier",                 "Roots_001_Zone_030.BP_Interactable_AddItem_C_0",            materials["parts_s5000_b"]),
    ("Ruins 4 - Nola",                                    "Ruins_001_Zone_004.EVT_ev_s_0020_NoraMeeting",              spirits["s5000_reaper"]),
    ("Ruins 5 - Charmed Fragment",                        "Ruins_001_Zone_005.BP_Interactable_AddItem_C_1",            stats["hp_up_s"]),
    ("Ruins 12 - Lito",                                   "Ruins_001_Zone_012.EVT_ev_s_e5030_Rogue_Defeat",            spirits["s5030_rogue"]),
    ("Ruins 12 - Subterranean Testing Site Key",          "Ruins_001_Zone_012.BP_Interactable_AddItem_Skill_C_0",      keys["key_ruins_tuto"]),
    ("Ruins 13 - Homunculus Research Log 1",              "Ruins_001_Zone_013.BP_Interactable_AddItem_C_1",            tips["tip_homunculusrecord_01"]),
    ("Ruins 14 - Worn Experiment Log",                    "Ruins_001_Zone_014.BP_Interactable_AddItem_C_1",            tips["tip_ruinsrecords_01"]),
    ("Ruins 15 - Healing Ward",                           "Ruins_001_Zone_015.EVT_ev_s_0015_GetHeal",                  aptitudes["heal"]),
    ("Sewer 1 - Corroded Warning Sign",                   "Sewer_001_Zone_001.BP_Interactable_AddItem_C_0",            tips["tip_corrosionboard_01"]),
    ("Sewer 2 - Grimoire",                                "Sewer_001_Zone_002.BP_Interactable_TreasureBox_C_1",        stats["shop_line_up"]),
    ("Sewer 4 - Materials",                               "Sewer_001_Zone_004.BP_Interactable_AddItem_C_1",            currencies["Default"]),
    ("Sewer 5 - Materials",                               "Sewer_001_Zone_005.BP_Interactable_AddItem_C_0",            currencies["Default"]),
    ("Sewer 8 - Eye of the Beast",                        "Sewer_001_Zone_008.BP_Interactable_AddItem_C_0",            passives["gold_up_1"]),
    ("Sewer 9 - Magic Strange Charm",                     "Sewer_001_Zone_009.BP_Interactable_AddItem_C_0",            passives["damage_up_maxhp_1"]),
    ("Sewer 9 - Materials",                               "Sewer_001_Zone_009.BP_Interactable_AddItem_C_2",            currencies["Default"]),
    ("Sewer 10 - Dive",                                   "Sewer_001_Zone_010.EVT_ev_s_0090_Sewer001.1",               aptitudes["dive"]),
    ("Sewer 10 - Blighted Note",                          "Sewer_001_Zone_010.EVT_ev_s_0090_Sewer001",                 tips["tip_disposaljournal_01"]),
    ("Sewer 11 - Charmed Fragment",                       "Sewer_001_Zone_011.BP_Interactable_AddItem_C_0",            stats["hp_up_s"]),
    ("Sewer 12 - Attuner's Pendant",                      "Sewer_001_Zone_012.BP_Interactable_AddItem_C_0",            passives["damage_up_swimming_1"]),
    ("Sewer 13 - Unidentified Core",                      "Sewer_001_Zone_013.BP_Interactable_AddItem_C_0",            materials["parts_s5000_a"]),
    ("Sewer 15 - Charmed Fragment",                       "Sewer_001_Zone_015.BP_Interactable_AddItem_C_0",            stats["hp_up_s"]),
    ("Sewer 17 - Chloe's Bracelet",                       "Sewer_001_Zone_017.BP_Interactable_TreasureBox_C_0",        equipments["armor_007"]),
    ("Slum 1 - Tattered Letter",                          "Slum_001_Zone_001.BP_Interactable_AddItem_C_1",             tips["tip_tunerletter_01"]),
    ("Slum 1 - Eye of the Homunculus",                    "Slum_001_Zone_001.BP_Interactable_AddItem_C_2",             passives["junk_up_1"]),
    ("Slum 1 - Levy's Mantle",                            "Slum_001_Zone_001.EVT_ev_n_Levy_Treasure4_002",             costumes["p0040"]),
    ("Slum 1 - Lower Stratum Key",                        "Slum_001_Zone_001.EVT_ev_s_0070_GordonReport.1",            keys["key_lower"]),
    ("Slum 1 - Fast Travel",                              "Slum_001_Zone_001.EVT_ev_s_0070_GordonReport",              aptitudes["fast_travel"]),
    ("Slum 1 - Charmed Ore",                              "Slum_001_Zone_001.EVT_ev_n_Levy_Treasure1_002",             stats["hp_up_l"]),
    ("Slum 2 - Charmed Fragment",                         "Slum_001_Zone_002.BP_Breakable_SpawnItem_Box_01_C_1",       stats["hp_up_s"]),
    ("Street 2 - Worries of a Sorcerer",                  "Street_001_Zone_002.BP_Interactable_AddItem_C_0",           tips["tip_painting_01"]),
    ("Street 3 - Sanguinary Raven",                       "Street_001_Zone_003.BP_Interactable_AddItem_C_0",           passives["damage_up_airborne_1"]),
    ("Street 4 - Yolvan",                                 "Street_001_Zone_004.EVT_ev_s_e5110_Gunman_Defeat",          spirits["s5110_gunman"]),
    ("Street 8 - Charmed Fragment",                       "Street_001_Zone_008.BP_Breakable_SpawnItem_Box_01_C_1",     stats["hp_up_s"]),
    ("Street 9 - Materials",                              "Street_001_Zone_009.BP_Interactable_AddItem_C_1",           currencies["Default"]),
    ("Street 12 - Attuner's Earrings",                    "Street_001_Zone_012.BP_Interactable_AddItem_C_0",           passives["onkill_restoresp_1"]),
    ("Street 14 - Crimson Ribbon",                        "Street_001_Zone_014.BP_Interactable_AddItem_C_1",           passives["debuff_cut_burn_1"]),
    ("Street 14 - Homunculus Expedition Report",          "Street_001_Zone_014.BP_Interactable_AddTutorial_C_1",       tips["tip_searchrecord_01"]),
    ("Street 17 - City Stratum Guard",                    "Street_001_Zone_017.EVT_ev_s_e0030_Guard_Defeat",           materials["parts_s5000_c"]),
    ("Street 18 - Materials",                             "Street_001_Zone_018.BP_Interactable_AddItem_C_0",           currencies["Default"]),
    ("Street 18 - Charmed Fragment",                      "Street_001_Zone_018.BP_Interactable_AddItem_C_1",           stats["hp_up_s"]),
    ("Street 19 - Charmed Fragment",                      "Street_001_Zone_019.BP_Interactable_AddItem_C_0",           stats["hp_up_s"]),
    ("Street 19 - Broken Warning Sign",                   "Street_001_Zone_019.BP_Interactable_AddItem_C_1",           tips["tip_tornletter_01"]),
    ("Street 20 - Tavern Bulletin Board",                 "Street_001_Zone_020.BP_Interactable_AddItem_C_0",           tips["tip_townboard_01"]),
    ("Street 21 - Materials",                             "Street_001_Zone_021.BP_Interactable_AddItem_C_0",           currencies["Default"]),
    ("Summit 1 - Upper Stratum Communication Device",     "Summit_001_Zone_001.BP_Interactable_AddItem_C_1",           tips["tip_upperterminal_01"]),
    ("Summit 4 - Administrator's Amplifier",              "Summit_001_Zone_004.BP_Interactable_AddItem_C_0",           materials["parts_lv6_b"]),
    ("Summit 7 - Administrator's Amplifier",              "Summit_001_Zone_007.BP_Interactable_AddItem_C_0",           materials["parts_lv6_b"]),
    ("Summit 8 - Administrator's Amplifier",              "Summit_001_Zone_008.BP_Interactable_AddItem_C_0",           materials["parts_lv6_b"]),
    ("Summit 9 - Scrap",                                  "Summit_001_Zone_009.BP_Interactable_AddItem_C_0",           currencies["rare"]),
    ("Summit 10 - Celestial Bangle",                      "Summit_001_Zone_010.BP_Interactable_TreasureBox_C_1",       equipments["armor_021"]),
    ("Summit 13 - Materials",                             "Summit_001_Zone_013.BP_Breakable_SpawnItem_Box_01_C_1",     currencies["Default"]),
    ("Summit 18 - Unidentified Transformer",              "Summit_001_Zone_018.BP_Interactable_AddItem_C_0",           materials["parts_s5000_c"]),
    ("Summit 21 - Velius",                                "Summit_001_Zone_021.EVT_ev_s_e0222_Security_Defeat",        materials["parts_lv6_b"]),
    ("Summit 22 - Administrator's Amplifier",             "Summit_001_Zone_022.BP_Interactable_AddItem_C_0",           materials["parts_lv6_b"]),
    ("Summit 22 - Charmed Fragment",                      "Summit_001_Zone_022.BP_Interactable_AddItem_C_1",           stats["hp_up_s"]),
    ("Summit 23 - Administrator's Amplifier",             "Summit_001_Zone_023.BP_Interactable_AddItem_C_0",           materials["parts_lv6_b"]),
    ("Summit 23 - Gilroy's Communication Device",         "Summit_001_Zone_023.BP_Interactable_AddItem_C_1",           tips["tip_gilroysterminal_01"]),
    ("Summit 23 - Nameless Priestess' Ring",              "Summit_001_Zone_023.BP_Interactable_TreasureBox_C_1",       passives["restore_sp_up_b_1"]),
    ("Summit 24 - Administrator's Amplifier 1",           "Summit_001_Zone_024.BP_Interactable_AddItem_C_0",           materials["parts_lv6_b"]),
    ("Summit 24 - Administrator's Amplifier 2",           "Summit_001_Zone_024.BP_Interactable_AddItem_C_1",           materials["parts_lv6_b"]),
    ("Summit 24 - Administrator's Amplifier 3",           "Summit_001_Zone_024.BP_Interactable_AddItem_C_2",           materials["parts_lv6_b"]),
    ("Summit 27 - Motley's Communication Device",         "Summit_001_Zone_027.BP_Interactable_AddItem_C_0",           tips["tip_motleysterminal_01"]),
    ("Summit 28 - Charmed Fragment",                      "Summit_001_Zone_028.BP_Interactable_AddItem_C_0",           stats["hp_up_s"]),
    ("Summit 30 - Charmed Fragment",                      "Summit_001_Zone_030.BP_Interactable_AddItem_C_0",           stats["hp_up_s"]),
    ("Swamp 2 - Materials",                               "Swamp_001_Zone_002.BP_Breakable_SpawnItem_Box_01_C_1",      currencies["Default"]),
    ("Swamp 2 - Letter in a Bottle",                      "Swamp_001_Zone_002.BP_Interactable_AddItem_C_2",            tips["tip_vials_01"]),
    ("Swamp 2 - Vivid Claws",                             "Swamp_001_Zone_002.BP_Interactable_AddItem_C_3",            passives["damage_up_targetdebuffed_1"]),
    ("Swamp 4 - Roller",                                  "Swamp_001_Zone_004.EVT_ev_s_e0203_Scarab_Defeat",           materials["parts_lv4_a"]),
    ("Swamp 6 - Obsolete Core",                           "Swamp_001_Zone_006.BP_Interactable_AddItem_C_1",            materials["parts_lv3_b"]),
    ("Swamp 6 - Magic Vial",                              "Swamp_001_Zone_006.BP_Interactable_AddItem_C_2",            stats["passive_slot_s"]),
    ("Swamp 7 - Silencing Light Documents",               "Swamp_001_Zone_007.BP_Interactable_AddItem_C_0",            tips["tip_lightsilence_01"]),
    ("Swamp 8 - Materials",                               "Swamp_001_Zone_008.BP_Breakable_SpawnItem_Pod_01_C_1",      currencies["Default"]),
    ("Swamp 9 - Journal of an Attuner",                   "Swamp_001_Zone_009.BP_Interactable_AddItem_C_0",            tips["tip_tornjournal_01"]),
    ("Swamp 10 - House Milius Earrings",                  "Swamp_001_Zone_010.BP_Interactable_AddItem_C_1",            passives["damage_up_skillcategory_auto_1"]),
    ("Swamp 10 - Grimoire",                               "Swamp_001_Zone_010.BP_Interactable_TreasureBox_C_1",        stats["shop_line_up"]),
    ("Swamp 12 - Charmed Fragment",                       "Swamp_001_Zone_012.BP_Interactable_AddItem_C_1",            stats["hp_up_s"]),
    ("Swamp 13 - Charmed Fragment",                       "Swamp_001_Zone_013.BP_Interactable_AddItem_C_0",            stats["hp_up_s"]),
    ("Swamp 15 - Motley",                                 "Swamp_001_Zone_015.EVT_ev_s_e6010_Cluster_Defeat",          aptitudes["Hook"]),
    ("Swamp 18 - Charmed Fragment",                       "Swamp_001_Zone_018.BP_Interactable_AddItem_C_1",            stats["hp_up_s"]),
    ("Swamp 19 - Materials",                              "Swamp_001_Zone_019.BP_Interactable_AddItem_C_1",            currencies["Default"]),
    ("Swamp 20 - Cleaner's Tag",                          "Swamp_001_Zone_020.BP_Interactable_AddItem_C_1",            passives["damage_up_targetstunned_1"]),
    ("Tower 1 - Charmed Fragment",                        "Tower_001_Zone_001.BP_Breakable_SpawnItem_Pod_01_C_1",      stats["hp_up_s"]),
    ("Tower 4 - Blighted Dice",                           "Tower_001_Zone_004.BP_Breakable_SpawnItem_Box_01_C_2",      passives["experience_up_1"]),
    ("Tower 4 - Magic Vial",                              "Tower_001_Zone_004.BP_Breakable_SpawnItem_Pod_01_C_2",      stats["passive_slot_s"]),
    ("Tower 6 - Materials",                               "Tower_001_Zone_006.BP_Interactable_AddItem_C_0",            currencies["Default"]),
    ("Tower 7 - Chief Attuner's Journal",                 "Tower_001_Zone_007.BP_Interactable_AddItem_C_1",            tips["tip_chieftunerjournal_01"]),
    ("Tower 7 - Magicite Mining Record",                  "Tower_001_Zone_007.BP_Interactable_AddTutorial_C_1",        tips["tip_magicrecord_01"]),
    ("Tower 9 - Charmed Fragment",                        "Tower_001_Zone_009.BP_Interactable_AddItem_C_1",            stats["hp_up_s"]),
    ("Tower 10 - Steeple Executioner",                    "Tower_001_Zone_010.EVT_ev_s_e0162_Gang_Defeat",             materials["parts_lv2_b"]),
    ("Tower 12 - Materials",                              "Tower_001_Zone_012.BP_Interactable_AddItem_C_1",            currencies["Default"]),
    ("Tower 14 - Book of the Blighted",                   "Tower_001_Zone_014.BP_Interactable_AddItem_C_1",            tips["tip_frostgrimoire_01"]),
    ("Tower 14 - Materials",                              "Tower_001_Zone_014.BP_Interactable_AddItem_C_2",            currencies["Default"]),
    ("Tower 14 - Grimoire",                               "Tower_001_Zone_014.BP_Interactable_TreasureBox_C_1",        stats["shop_line_up"]),
    ("Tower 14 - Pure Floral Necklace",                   "Tower_001_Zone_014.BP_Interactable_TreasureBox_C_2",        passives["damage_up_skillcategory_repeat_1"]),
    ("Tower 15 - Charmed Fragment",                       "Tower_001_Zone_015.BP_Interactable_AddItem_C_1",            stats["hp_up_s"]),
    ("Tower 16 - Shackled Beast",                         "Tower_001_Zone_016.EVT_ev_s_e5060_Beast_Defeat",            spirits["s5060_beast"]),
    ("Tower 18 - Homunculus Research Log 2",              "Tower_001_Zone_018.BP_Interactable_AddItem_C_0",            tips["tip_homunculusrecord_02"]),
    ("Tower 19 - Eye of the Ancients",                    "Tower_001_Zone_019.BP_Interactable_TreasureBox_C_1",        passives["reduce_skill_cooldown_1"]),
]

event_locations: Dict[str, LocationData] = {location.name: location for location in [
    LocationData("Goal", content=events["Victory"]),
    LocationData("Ruins 7 - Lever", content=events["Ruins 7 Lever"]),
]}

locations: Dict[str, LocationData] = {location.name: location for location in 
    [LocationData(name, index, key, content) for index, (name, key, content) in enumerate(locations_data)]}
