from os import name
from typing import List, Optional, Dict
from enum import Enum
from .Items import ItemData, items, events, assists, aptitudes, costumes, currencies,\
   equipments, quests, keys, materials, passives, skills, spirits, stats, tips
from dataclasses import dataclass


class LocationGroup(Enum):
    """
    Used to group locations
    """

    Boss = 0
    Event = 1
    Interactable = 2


@dataclass
class LocationData:
    name: str
    address: Optional[int] = None
    key: Optional[str] = None
    content: Optional[ItemData] = None
    group: Optional[LocationGroup] = None

locations_data = [
    ("Center 1"		, "Center_001_Zone_001.EVT_ev_s_e6050_Master_Defeat"		, aptitudes["SP"]),
    ("Center 1"		, "Center_001_Zone_001.BP_Interactable_AddItem_C_1"			, materials["parts_lv6_a"]),
    ("Center 1"		, "Center_001_Zone_001.EVT_ev_n_Levy_Treasure3_002"			, spirits["s5080_hawk"]),
    ("Center 2"		, "Center_001_Zone_002.EVT_ev_n_Center_costume_001"			, costumes["p0030"]),
    ("Center 3"		, "Center_001_Zone_003.BP_Breakable_SpawnItem_Pod_01_C_1"	, stats["hp_up_s"]),
    ("Center 4"		, "Center_001_Zone_004.EVT_ev_n_Levy_Treasure6_002"			, quests["quest_amulet"]),

    ("Crossroad 2"	, "Crossroad_001_Zone_002.BP_Interactable_AddItem_C_1"		, stats["hp_up_s"]),
    ("Crossroad 3"	, "Crossroad_001_Zone_003.BP_Interactable_AddItem_C_1"		, tips["tip_workerscode_01"]),
    ("Crossroad 5"	, "Crossroad_001_Zone_005.EVT_ev_s_0050_LevyMeeting.1"		, aptitudes["dodge"]),
    ("Crossroad 5"	, "Crossroad_001_Zone_005.EVT_ev_s_0050_LevyMeeting"		, aptitudes["double_jump"]),

    ("Estate 2"		, "Estate_001_Zone_002.EVT_ev_s_n5040_Maiden_Defeat.1"		, keys["key_higher_a"]),
    ("Estate 2"		, "Estate_001_Zone_002.EVT_ev_s_n5040_Maiden_Defeat"		, spirits["s5040_maiden"]),
    ("Estate 3"		, "Estate_001_Zone_003.BP_Interactable_AddItem_C_0"			, materials["parts_lv5_a"]),
    ("Estate 4"		, "Estate_001_Zone_004.BP_Interactable_AddItem_C_0"			, equipments["armor_014"]),
    ("Estate 5"		, "Estate_001_Zone_005.BP_Interactable_AddItem_C_0"			, currencies["rare"]),
    ("Estate 6"		, "Estate_001_Zone_006.BP_Interactable_AddItem_C_0"			, tips["tip_frostsrecord_02"]),
    ("Estate 7"		, "Estate_001_Zone_007.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Estate 7"		, "Estate_001_Zone_007.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Estate 7"		, "Estate_001_Zone_007.BP_Trigger_Event_LevyTreasure_C_1"	, quests["quest_artifact"]),
    ("Estate 8"		, "Estate_001_Zone_008.BP_Interactable_AddItem_C_1"			, currencies["rare"]),
    ("Estate 1"		, "Estate_001_Zone_010.BP_Interactable_TreasureBox_C_1"		, stats["shop_line_up"]),
    ("Estate 11"	, "Estate_001_Zone_011.BP_Interactable_AddItem_C_0"			, materials["parts_lv5_a"]),
    ("Estate 12"	, "Estate_001_Zone_012.BP_Interactable_AddItem_C_0"			, tips["tip_frostsrecord_01"]),

    ("Factory 1"	, "Factory_001_Zone_001.BP_Interactable_AddItem_C_0"		, materials["parts_lv5_a"]),
    ("Factory 1"	, "Factory_001_Zone_001.BP_Interactable_AddItem_C_1"		, passives["stamina_damage_up_b_1"]),
    ("Factory 2"	, "Factory_001_Zone_002.BP_Interactable_AddItem_C_0"		, tips["tip_surveillancerecord_01"]),
    ("Factory 5"	, "Factory_001_Zone_005.BP_Interactable_AddItem_C_0"		, currencies["rare"]),
    ("Factory 6"	, "Factory_001_Zone_006.BP_Interactable_TreasureBox_C_0"	, passives["damage_cut_debuff_down_1"]),
    ("Factory 7"	, "Factory_001_Zone_007.BP_Interactable_AddItem_C_0"		, tips["tip_administrationrecord_01"]),
    ("Factory 8"	, "Factory_001_Zone_008.BP_Interactable_AddItem_C_1"		, currencies["rare"]),
    ("Factory 9"	, "Factory_001_Zone_009.BP_Interactable_AddItem_C_0"		, stats["hp_up_s"]),
    ("Factory 1"	, "Factory_001_Zone_010.EVT_ev_s_e2030_Sector_Defeat"		, materials["parts_lv5_b"]),
    ("Factory 12"	, "Factory_001_Zone_012.BP_Interactable_AddItem_C_1"		, currencies["rare"]),
    ("Factory 12"	, "Factory_001_Zone_012.BP_Interactable_TreasureBox_C_1"	, passives["onattack_restorehp_damage_1"]),
    ("Factory 13"	, "Factory_001_Zone_013.BP_Interactable_AddItem_C_0"		, stats["hp_up_s"]),
    ("Factory 14"	, "Factory_001_Zone_014.BP_Interactable_TreasureBox_C_1"	, stats["shop_line_up"]),
    ("Factory 15"	, "Factory_001_Zone_015.BP_Interactable_AddItem_C_0"		, stats["hp_up_s"]),
    ("Factory 15"	, "Factory_001_Zone_015.BP_Interactable_AddItem_C_1"		, stats["passive_slot_s"]),
    ("Factory 18"	, "Factory_001_Zone_018.BP_Interactable_AddItem_C_1"		, tips["tip_enhancementplan_01"]),
    ("Factory 18"	, "Factory_001_Zone_018.EVT_ev_s_5200_Pounder_Upgrade"		, aptitudes["high_jump"]),
    ("Factory 19"	, "Factory_001_Zone_019.BP_Interactable_AddItem_C_1"		, currencies["rare"]),
    ("Factory 19"	, "Factory_001_Zone_019.BP_Trigger_Event_LevyTreasure_C_0"	, quests["quest_stone"]),
    ("Factory 21"	, "Factory_001_Zone_021.EVT_ev_s_0250_KeyFactory.1"			, tips["tip_towerumbrella_01"]),
    ("Factory 21"	, "Factory_001_Zone_021.EVT_ev_s_0250_KeyFactory"			, keys["key_higher_b"]),

    ("Forest 1"		, "Forest_001_Zone_001.BP_Interactable_AddItem_C_1"			, equipments["armor_008"]),
    ("Forest 2"		, "Forest_001_Zone_002.BP_Interactable_AddItem_C_1"			, materials["parts_lv3_b"]),
    ("Forest 2"		, "Forest_001_Zone_002.BP_Interactable_AddTutorial_C_1"		, tips["tip_tombstone_01"]),
    ("Forest 4"		, "Forest_001_Zone_004.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Forest 7"		, "Forest_001_Zone_007.BP_Interactable_AddItem_C_1"			, passives["damage_up_grounded_1"]),
    ("Forest 9"		, "Forest_001_Zone_009.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Forest 9"		, "Forest_001_Zone_009.BP_Interactable_AddItem_C_3"			, currencies["Default"]),
    ("Forest 9"		, "Forest_001_Zone_009.BP_Interactable_AddItem_C_5"			, passives["damage_cut_minhp_1"]),
    ("Forest 1"		, "Forest_001_Zone_010.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Forest 1"		, "Forest_001_Zone_010.BP_Interactable_AddItem_C_2"			, currencies["Default"]),
    ("Forest 11"	, "Forest_001_Zone_011.BP_Interactable_AddItem_C_1"			, stats["passive_slot_s"]),
    ("Forest 19"	, "Forest_001_Zone_019.BP_Interactable_AddItem_C_1"			, passives["damage_cut_maxhp_1"]),
    ("Forest 2"		, "Forest_001_Zone_020.BP_Interactable_AddItem_C_0"			, tips["tip_secretletter_01"]),
    ("Forest 2"		, "Forest_001_Zone_020.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Forest 2"		, "Forest_001_Zone_020.BP_Interactable_TreasureBox_C_1"		, stats["shop_line_up"]),
    ("Forest 23"	, "Forest_001_Zone_023.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Forest 23"	, "Forest_001_Zone_023.BP_Interactable_AddItem_C_3"			, tips["tip_cassiabook_01"]),
    ("Forest 23"	, "Forest_001_Zone_023.EVT_ev_n_Levy_Treasure2_002"			, passives["reduce_gravity"]),
    ("Forest 23"	, "Forest_001_Zone_023.EVT_ev_s_5210_Fenris_Upgrade"		, aptitudes["dash_charge"]),

    ("Garden 1"		, "Garden_001_Zone_001.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Garden 1"		, "Garden_001_Zone_001.BP_Interactable_AddItem_C_2"			, stats["hp_up_s"]),
    ("Garden 1"		, "Garden_001_Zone_001.BP_Interactable_AddItem_C_4"			, currencies["Default"]),
    ("Garden 1"		, "Garden_001_Zone_001.BP_Interactable_TreasureBox_C_1"		, passives["damage_cut_debuffed_1"]),
    ("Garden 2"		, "Garden_001_Zone_002.BP_Interactable_TreasureBox_C_1"		, passives["debuff_damage_up_b_1"]),
    ("Garden 2"		, "Garden_001_Zone_002.BP_Interactable_TreasureBox_C_3"		, assists["assist_009"]),
    ("Garden 3"		, "Garden_001_Zone_003.BP_Interactable_AddItem_C_1"			, stats["shop_line_up"]),
    ("Garden 3"		, "Garden_001_Zone_003.BP_Interactable_AddItem_C_2"			, tips["tip_engineermemoirs_01"]),
    ("Garden 3"		, "Garden_001_Zone_003.BP_Interactable_AddItem_C_3"			, tips["tip_miliusbook_01"]),
    ("Garden 3"		, "Garden_001_Zone_003.BP_Interactable_AddItem_C_4"			, tips["tip_landend_01"]),
    ("Garden 3"		, "Garden_001_Zone_003.BP_Interactable_AddItem_C_5"			, passives["damage_up_debuffed_1"]),
    ("Garden 5"		, "Garden_001_Zone_005.EVT_ev_s_0233_Researcher_002"		, materials["parts_lv4_b"]),
    ("Garden 5"		, "Garden_001_Zone_005.EVT_ev_n_Levy_Treasure5_002"			, stats["passive_slot_l"]),
    ("Garden 6"		, "Garden_001_Zone_006.BP_Breakable_SpawnItem_Pod_01_C_1"	, stats["passive_slot_s"]),
    ("Garden 6"		, "Garden_001_Zone_006.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Garden 6"		, "Garden_001_Zone_006.BP_Interactable_AddItem_C_2"			, materials["parts_lv6_a"]),
    ("Garden 6"		, "Garden_001_Zone_006.BP_Interactable_TreasureBox_C_1"		, materials["parts_s5000_b"]),
    ("Garden 7"		, "Garden_001_Zone_007.BP_Interactable_AddItem_C_1"			, equipments["shield_009"]),
    ("Garden 8"		, "Garden_001_Zone_008.BP_Interactable_AddItem_C_1"			, currencies["rare"]),
    ("Garden 11"	, "Garden_001_Zone_011.EVT_ev_s_e5070_Witch_Defeat"			, spirits["s5070_witch"]),
    ("Garden 14"	, "Garden_001_Zone_014.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),

    ("Kowloon 5"	, "Kowloon_001_Zone_005.BP_Interactable_AddItem_C_0"		, tips["tip_mothersnote_01"]),
    ("Kowloon 8"	, "Kowloon_001_Zone_008.BP_Interactable_AddItem_C_1"		, passives["restore_sp_up_a_1"]),
    ("Kowloon 9"	, "Kowloon_001_Zone_009.BP_Trigger_Event_LevyTreasure_C_0"	, quests["quest_bird"]),
    ("Kowloon 13"	, "Kowloon_001_Zone_013.BP_Interactable_AddItem_C_1"		, currencies["rare"]),
    ("Kowloon 18"	, "Kowloon_001_Zone_018.BP_Interactable_AddItem_C_0"		, stats["hp_up_s"]),
    ("Kowloon 21"	, "Kowloon_001_Zone_021.BP_Interactable_AddItem_C_1"		, materials["parts_lv4_b"]),
    ("Kowloon 26"	, "Kowloon_001_Zone_026.BP_Interactable_AddItem_C_0"		, currencies["Default"]),
    ("Kowloon 28"	, "Kowloon_001_Zone_028.BP_Interactable_AddItem_C_0"		, passives["damage_up_skillcategory_defence_1"]),
    ("Kowloon 28"	, "Kowloon_001_Zone_028.BP_Interactable_AddItem_C_1"		, materials["parts_lv4_b"]),
    ("Kowloon 29"	, "Kowloon_001_Zone_029.BP_Interactable_AddItem_C_0"		, currencies["rare"]),
    ("Kowloon 31"	, "Kowloon_001_Zone_031.BP_Interactable_TreasureBox_C_0"	, stats["shop_line_up"]),
    ("Kowloon 32"	, "Kowloon_001_Zone_032.BP_Interactable_AddItem_C_0"		, tips["tip_fightingtower_01"]),
    ("Kowloon 33"	, "Kowloon_001_Zone_033.BP_Interactable_AddItem_C_0"		, tips["tip_researchersjournal_01"]),
    ("Kowloon 35"	, "Kowloon_001_Zone_035.BP_Interactable_AddItem_C_0"		, stats["hp_up_s"]),
    ("Kowloon 36"	, "Kowloon_001_Zone_036.BP_Interactable_AddItem_C_0"		, passives["onkill_reduce_cooldowns_1"]),
    ("Kowloon 39"	, "Kowloon_001_Zone_039.BP_Interactable_AddItem_C_0"		, stats["passive_slot_s"]),
    ("Kowloon 39"	, "Kowloon_001_Zone_039.BP_Interactable_AddItem_C_1"		, currencies["Default"]),
    ("Kowloon 39"	, "Kowloon_001_Zone_039.BP_Interactable_TreasureBox_C_0"	, assists["assist_006"]),
    ("Kowloon 47"	, "Kowloon_001_Zone_047.BP_Interactable_AddItem_C_0"		, stats["hp_up_s"]),
    ("Kowloon 47"	, "Kowloon_001_Zone_047.BP_Interactable_AddItem_C_2"		, materials["parts_lv6_a"]),
    ("Kowloon 51"	, "Kowloon_001_Zone_051.EVT_ev_s_e5050_Ronin_Defeat"		, spirits["s5050_ronin"]),

    ("Labo 1"		, "Labo_001_Zone_001.BP_Interactable_AddItem_C_0"			, tips["tip_liliasdiary_01"]),
    ("Labo 3"		, "Labo_001_Zone_003.EVT_ev_s_e5003_Reaper_Defeat"			, materials["parts_s5000_a"]),
    ("Labo 6"		, "Labo_001_Zone_006.BP_Interactable_TreasureBox_C_0"		, passives["damage_up_skillcategory_combo_1"]),
    ("Labo 7"		, "Labo_001_Zone_007.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Labo 8"		, "Labo_001_Zone_008.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Labo 9"		, "Labo_001_Zone_009.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Labo 1"		, "Labo_001_Zone_010.BP_Interactable_TreasureBox_C_1"		, stats["passive_slot_s"]),
    ("Labo 11"		, "Labo_001_Zone_011.BP_Interactable_AddItem_C_0"			, currencies["rare"]),
    ("Labo 17"		, "Labo_001_Zone_017.BP_Interactable_AddItem_C_0"			, passives["damage_cut_sp_gauge_1"]),
    ("Labo 18"		, "Labo_001_Zone_018.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Labo 18"		, "Labo_001_Zone_018.BP_Interactable_AddItem_C_2"			, passives["damage_up_sp_gauge_1"]),
    ("Labo 19"		, "Labo_001_Zone_019.BP_Interactable_AddItem_C_0"			, currencies["rare"]),
    ("Labo 21"		, "Labo_001_Zone_021.EVT_ev_s_5230_Finder_Upgrade"			, aptitudes["wall_charge"]),
    ("Labo 22"		, "Labo_001_Zone_022.BP_Interactable_AddItem_C_0"			, tips["tip_gilroyrecords_01"]),
    ("Labo 24"		, "Labo_001_Zone_024.BP_Interactable_AddItem_C_0"			, tips["tip_caladriusrecord_01"]),
    ("Labo 24"		, "Labo_001_Zone_024.BP_Interactable_TreasureBox_C_0"		, stats["shop_line_up"]),
    ("Labo 26"		, "Labo_001_Zone_026.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Labo 27"		, "Labo_001_Zone_027.BP_Interactable_TreasureBox_C_1"		, materials["parts_lv6_a"]),

    ("Mine 2"		, "Mine_001_Zone_002.BP_Interactable_AddItem_C_1"			, passives["onkill_restorehp_1"]),
    ("Mine 4"		, "Mine_001_Zone_004.EVT_ev_s_e0122_Wheeler_Defeat"			, materials["parts_lv2_b"]),
    ("Mine 4"		, "Mine_001_Zone_004.BP_Interactable_AddItem_C_1"			, tips["tip_writingwall_01"]),
    ("Mine 5"		, "Mine_001_Zone_005.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Mine 5"		, "Mine_001_Zone_005.BP_Interactable_AddItem_C_2"			, currencies["Default"]),
    ("Mine 5"		, "Mine_001_Zone_005.BP_Interactable_AddItem_C_3"			, stats["passive_slot_s"]),
    ("Mine 6"		, "Mine_001_Zone_006.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Mine 6"		, "Mine_001_Zone_006.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Mine 8"		, "Mine_001_Zone_008.BP_Interactable_AddItem_C_0"			, materials["parts_s5000_b"]),
    ("Mine 9"		, "Mine_001_Zone_009.EVT_ev_s_0080_FrostAndOwl"				, spirits["s5090_owl"]),
    ("Mine 11"		, "Mine_001_Zone_011.BP_Interactable_TreasureBox_C_1"		, passives["damage_cut_physic_1"]),
    ("Mine 12"		, "Mine_001_Zone_012.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Mine 13"		, "Mine_001_Zone_013.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Mine 13"		, "Mine_001_Zone_013.BP_Interactable_TreasureBox_C_1"		, stats["shop_line_up"]),
    ("Mine 14"		, "Mine_001_Zone_014.BP_Interactable_AddItem_C_0"			, tips["tip_tunerjournal_01"]),
    ("Mine 14"		, "Mine_001_Zone_014.BP_Trigger_Event_LevyTreasure_C_0"		, quests["quest_board"]),
    ("Mine 17"		, "Mine_001_Zone_017.EVT_ev_s_e5200_Pounder_Defeat"			, aptitudes["pile_attack"]),

    ("Paradise 1"	, "Paradise_001_Zone_001.BP_Interactable_AddItem_C_1"		, stats["hp_up_s"]),
    ("Paradise 1"	, "Paradise_001_Zone_001.BP_Interactable_AddItem_C_2"		, stats["hp_up_s"]),
    ("Paradise 2"	, "Paradise_001_Zone_002.BP_Interactable_AddItem_C_0"		, tips["tip_degrandsrecord_01"]),
    ("Paradise 3"	, "Paradise_001_Zone_003.BP_Interactable_AddItem_C_0"		, stats["passive_slot_s"]),
    ("Paradise 3"	, "Paradise_001_Zone_003.BP_Interactable_TreasureBox_C_0"	, stats["shop_line_up"]),
    ("Paradise 5"	, "Paradise_001_Zone_005.BP_Interactable_AddItem_C_0"		, stats["hp_up_s"]),
    ("Paradise 8"	, "Paradise_001_Zone_008.EVT_ev_s_e0289_Banshee_Defeat"		, materials["parts_lv5_b"]),
    ("Paradise 11"	, "Paradise_001_Zone_011.BP_Interactable_AddItem_C_0"		, tips["tip_bloodstaineddiary_01"]),
    ("Paradise 12"	, "Paradise_001_Zone_012.BP_Interactable_TreasureBox_C_0"	, passives["onattack_restorehp_1"]),
    ("Paradise 19"	, "Paradise_001_Zone_019.BP_Interactable_AddItem_C_0"		, currencies["rare"]),
    ("Paradise 19"	, "Paradise_001_Zone_019.BP_Interactable_AddItem_C_1"		, currencies["Default"]),
    ("Paradise 19"	, "Paradise_001_Zone_019.EVT_ev_s_5220_Wirer_Upgrade"		, aptitudes["dash_charge_underwater"]),
    ("Paradise 21"	, "Paradise_001_Zone_021.BP_Interactable_AddItem_C_0"		, currencies["Default"]),
    ("Paradise 24"	, "Paradise_001_Zone_024.BP_Interactable_AddItem_C_0"		, tips["tip_prisonwall_01"]),
    ("Paradise 26"	, "Paradise_001_Zone_026.BP_Interactable_AddItem_C_0"		, equipments["armor_015"]),
    ("Paradise 3"	, "Paradise_001_Zone_030.EVT_ev_n_e0289_Banshee_KeyGet"		, keys["key_owner"]),
    ("Paradise 32"	, "Paradise_001_Zone_032.BP_Interactable_AddItem_C_0"		, materials["parts_s5000_c"]),
    ("Paradise 33"	, "Paradise_001_Zone_033.BP_Interactable_AddItem_C_0"		, passives["onkill_drops_1"]),
    ("Paradise 34"	, "Paradise_001_Zone_034.BP_Interactable_TreasureBox_C_1"	, passives["damage_up_skillcategory_special_1"]),

    ("Quarry 1"		, "Quarry_001_Zone_001.BP_Interactable_AddTutorial_C_0"		, tips["tip_freeze_01"]),
    ("Quarry 2"		, "Quarry_001_Zone_002.BP_Interactable_AddItem_C_2"			, stats["hp_up_s"]),
    ("Quarry 3"		, "Quarry_001_Zone_003.BP_Interactable_AddItem_C_0"			, tips["tip_raggedpastedown_01"]),
    ("Quarry 3"		, "Quarry_001_Zone_003.BP_Trigger_Event_LevyTreasure_C_0"	, quests["quest_perfume"]),
    ("Quarry 4"		, "Quarry_001_Zone_004.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Quarry 4"		, "Quarry_001_Zone_004.BP_Interactable_TreasureBox_C_1"		, stats["shop_line_up"]),
    ("Quarry 5"		, "Quarry_001_Zone_005.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Quarry 7"		, "Quarry_001_Zone_007.BP_Interactable_AddItem_C_1"			, passives["debuff_damage_up_a_1"]),
    ("Quarry 1"		, "Quarry_001_Zone_010.BP_Interactable_AddItem_C_1"			, materials["parts_lv4_a"]),
    ("Quarry 11"	, "Quarry_001_Zone_011.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Quarry 14"	, "Quarry_001_Zone_014.BP_Interactable_AddItem_C_1"			, stats["passive_slot_s"]),
    ("Quarry 15"	, "Quarry_001_Zone_015.BP_Interactable_AddItem_C_1"			, tips["tip_lowestrecord_01"]),
    ("Quarry 15"	, "Quarry_001_Zone_015.BP_Interactable_AddItem_C_3"			, stats["hp_up_s"]),
    ("Quarry 15"	, "Quarry_001_Zone_015.BP_Interactable_TreasureBox_C_1"		, assists["assist_001"]),
    ("Quarry 16"	, "Quarry_001_Zone_016.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Quarry 17"	, "Quarry_001_Zone_017.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Quarry 18"	, "Quarry_001_Zone_018.BP_Interactable_AddItem_C_1"			, passives["stamina_damage_up_a_1"]),
    ("Quarry 21"	, "Quarry_001_Zone_021.BP_Interactable_AddItem_C_1"			, materials["parts_s5000_a"]),
    ("Quarry 21"	, "Quarry_001_Zone_021.BP_Interactable_AddItem_C_2"			, passives["damage_up_minhp_1"]),
    ("Quarry 24"	, "Quarry_001_Zone_024.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Quarry 31"	, "Quarry_001_Zone_031.EVT_ev_s_n7043_Quarry_Tuner"			, aptitudes["wall_grab"]),

    ("Roots 1"		, "Roots_001_Zone_001.EVT_ev_s_e5012_RootsLancer_Defeat.1"	, quests["quest_eye"]),
    ("Roots 1"		, "Roots_001_Zone_001.EVT_ev_s_e5012_RootsLancer_Defeat"	, spirits["s5010_lancer"]),
    ("Roots 2"		, "Roots_001_Zone_002.EVT_ev_s_FinalRelic.1"				, costumes["p0050"]),
    ("Roots 2"		, "Roots_001_Zone_002.EVT_ev_s_FinalRelic"					, passives["ending_flag"]),
    ("Roots 5"		, "Roots_001_Zone_005.EVT_ev_n_Levy_Treasure6_001"			, quests["quest_lithograph"]),
    ("Roots 6"		, "Roots_001_Zone_006.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Roots 6"		, "Roots_001_Zone_006.BP_Interactable_AddItem_C_3"			, materials["parts_lv6_a"]),
    ("Roots 8"		, "Roots_001_Zone_008.BP_Interactable_AddItem_C_1"			, stats["hp_up_l"]),
    ("Roots 9"		, "Roots_001_Zone_009.BP_Interactable_TreasureBox_C_1"		, currencies["Default"]),
    ("Roots 11"		, "Roots_001_Zone_011.BP_Interactable_AddItem_C_1"			, tips["tip_prophecybook_01"]),
    ("Roots 12"		, "Roots_001_Zone_012.BP_Interactable_AddItem_C_1"			, assists["assist_010"]),
    ("Roots 17"		, "Roots_001_Zone_017.BP_Interactable_AddItem_C_1"			, tips["tip_yoransdiary_01"]),
    ("Roots 18"		, "Roots_001_Zone_018.BP_Interactable_AddItem_C_0"			, tips["tip_yoransdiary_02"]),
    ("Roots 2"		, "Roots_001_Zone_020.BP_Interactable_TreasureBox_C_0"		, equipments["shield_008"]),
    ("Roots 22"		, "Roots_001_Zone_022.BP_Interactable_TreasureBox_C_1"		, passives["onattack_instantkill_1"]),
    ("Roots 23"		, "Roots_001_Zone_023.BP_Interactable_AddItem_C_0"			, materials["parts_lv6_a"]),
    ("Roots 27"		, "Roots_001_Zone_027.BP_Interactable_TreasureBox_C_0"		, equipments["armor_020"]),
    ("Roots 28"		, "Roots_001_Zone_028.BP_Interactable_AddItem_C_0"			, materials["parts_lv6_a"]),
    ("Roots 29"		, "Roots_001_Zone_029.BP_Interactable_AddItem_C_0"			, stats["hp_up_l"]),
    ("Roots 3"		, "Roots_001_Zone_030.BP_Interactable_AddItem_C_0"			, materials["parts_s5000_b"]),

    ("Ruins 4"		, "Ruins_001_Zone_004.EVT_ev_s_0020_NoraMeeting"			, spirits["s5000_reaper"]),
    ("Ruins 5"		, "Ruins_001_Zone_005.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Ruins 12"		, "Ruins_001_Zone_012.EVT_ev_s_e5030_Rogue_Defeat"			, spirits["s5030_rogue"]),
    ("Ruins 12"		, "Ruins_001_Zone_012.BP_Interactable_AddItem_Skill_C_0"	, keys["key_ruins_tuto"]),
    ("Ruins 13"		, "Ruins_001_Zone_013.BP_Interactable_AddItem_C_1"			, tips["tip_homunculusrecord_01"]),
    ("Ruins 14"		, "Ruins_001_Zone_014.BP_Interactable_AddItem_C_1"			, tips["tip_ruinsrecords_01"]),
    ("Ruins 15"		, "Ruins_001_Zone_015.EVT_ev_s_0015_GetHeal"				, aptitudes["heal"]),

    ("Sewer 1"		, "Sewer_001_Zone_001.BP_Interactable_AddItem_C_0"			, tips["tip_corrosionboard_01"]),
    ("Sewer 2"		, "Sewer_001_Zone_002.BP_Interactable_TreasureBox_C_1"		, stats["shop_line_up"]),
    ("Sewer 4"		, "Sewer_001_Zone_004.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Sewer 5"		, "Sewer_001_Zone_005.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Sewer 8"		, "Sewer_001_Zone_008.BP_Interactable_AddItem_C_0"			, passives["gold_up_1"]),
    ("Sewer 9"		, "Sewer_001_Zone_009.BP_Interactable_AddItem_C_0"			, passives["damage_up_maxhp_1"]),
    ("Sewer 9"		, "Sewer_001_Zone_009.BP_Interactable_AddItem_C_2"			, currencies["Default"]),
    ("Sewer 1"		, "Sewer_001_Zone_010.EVT_ev_s_0090_Sewer001.1"				, aptitudes["dive"]),
    ("Sewer 1"		, "Sewer_001_Zone_010.EVT_ev_s_0090_Sewer001"				, tips["tip_disposaljournal_01"]),
    ("Sewer 11"		, "Sewer_001_Zone_011.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Sewer 12"		, "Sewer_001_Zone_012.BP_Interactable_AddItem_C_0"			, passives["damage_up_swimming_1"]),
    ("Sewer 13"		, "Sewer_001_Zone_013.BP_Interactable_AddItem_C_0"			, materials["parts_s5000_a"]),
    ("Sewer 15"		, "Sewer_001_Zone_015.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Sewer 17"		, "Sewer_001_Zone_017.BP_Interactable_TreasureBox_C_0"		, equipments["armor_007"]),

    ("Slum 1"		, "Slum_001_Zone_001.BP_Interactable_AddItem_C_1"			, tips["tip_tunerletter_01"]),
    ("Slum 1"		, "Slum_001_Zone_001.BP_Interactable_AddItem_C_2"			, passives["junk_up_1"]),
    ("Slum 1"		, "Slum_001_Zone_001.EVT_ev_n_Levy_Treasure4_002"			, costumes["p0040"]),
    ("Slum 1"		, "Slum_001_Zone_001.EVT_ev_s_0070_GordonReport.1"			, keys["key_lower"]),
    ("Slum 1"		, "Slum_001_Zone_001.EVT_ev_s_0070_GordonReport"			, aptitudes["fast_travel"]),
    ("Slum 1"		, "Slum_001_Zone_001.EVT_ev_n_Levy_Treasure1_002"			, stats["hp_up_l"]),
    ("Slum 2"		, "Slum_001_Zone_002.BP_Breakable_SpawnItem_Box_01_C_1"		, stats["hp_up_s"]),

    ("Street 2"		, "Street_001_Zone_002.BP_Interactable_AddItem_C_0"			, tips["tip_painting_01"]),
    ("Street 3"		, "Street_001_Zone_003.BP_Interactable_AddItem_C_0"			, passives["damage_up_airborne_1"]),
    ("Street 4"		, "Street_001_Zone_004.EVT_ev_s_e5110_Gunman_Defeat"		, spirits["s5110_gunman"]),
    ("Street 8"		, "Street_001_Zone_008.BP_Breakable_SpawnItem_Box_01_C_1"	, stats["hp_up_s"]),
    ("Street 9"		, "Street_001_Zone_009.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Street 12"	, "Street_001_Zone_012.BP_Interactable_AddItem_C_0"			, passives["onkill_restoresp_1"]),
    ("Street 14"	, "Street_001_Zone_014.BP_Interactable_AddItem_C_1"			, passives["debuff_cut_burn_1"]),
    ("Street 14"	, "Street_001_Zone_014.BP_Interactable_AddTutorial_C_1"		, tips["tip_searchrecord_01"]),
    ("Street 17"	, "Street_001_Zone_017.EVT_ev_s_e0030_Guard_Defeat"			, materials["parts_s5000_c"]),
    ("Street 18"	, "Street_001_Zone_018.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Street 18"	, "Street_001_Zone_018.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Street 19"	, "Street_001_Zone_019.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Street 19"	, "Street_001_Zone_019.BP_Interactable_AddItem_C_1"			, tips["tip_tornletter_01"]),
    ("Street 2"		, "Street_001_Zone_020.BP_Interactable_AddItem_C_0"			, tips["tip_townboard_01"]),
    ("Street 21"	, "Street_001_Zone_021.BP_Interactable_AddItem_C_0"			, currencies["Default"]),

    ("Summit 1"		, "Summit_001_Zone_001.BP_Interactable_AddItem_C_1"			, tips["tip_upperterminal_01"]),
    ("Summit 4"		, "Summit_001_Zone_004.BP_Interactable_AddItem_C_0"			, materials["parts_lv6_b"]),
    ("Summit 7"		, "Summit_001_Zone_007.BP_Interactable_AddItem_C_0"			, materials["parts_lv6_b"]),
    ("Summit 8"		, "Summit_001_Zone_008.BP_Interactable_AddItem_C_0"			, materials["parts_lv6_b"]),
    ("Summit 9"		, "Summit_001_Zone_009.BP_Interactable_AddItem_C_0"			, currencies["rare"]),
    ("Summit 1"		, "Summit_001_Zone_010.BP_Interactable_TreasureBox_C_1"		, equipments["armor_021"]),
    ("Summit 13"	, "Summit_001_Zone_013.BP_Breakable_SpawnItem_Box_01_C_1"	, currencies["Default"]),
    ("Summit 18"	, "Summit_001_Zone_018.BP_Interactable_AddItem_C_0"			, materials["parts_s5000_c"]),
    ("Summit 21"	, "Summit_001_Zone_021.EVT_ev_s_e0222_Security_Defeat"		, materials["parts_lv6_b"]),
    ("Summit 22"	, "Summit_001_Zone_022.BP_Interactable_AddItem_C_0"			, materials["parts_lv6_b"]),
    ("Summit 22"	, "Summit_001_Zone_022.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Summit 23"	, "Summit_001_Zone_023.BP_Interactable_AddItem_C_0"			, materials["parts_lv6_b"]),
    ("Summit 23"	, "Summit_001_Zone_023.BP_Interactable_AddItem_C_1"			, tips["tip_gilroysterminal_01"]),
    ("Summit 23"	, "Summit_001_Zone_023.BP_Interactable_TreasureBox_C_1"		, passives["restore_sp_up_b_1"]),
    ("Summit 24"	, "Summit_001_Zone_024.BP_Interactable_AddItem_C_0"			, materials["parts_lv6_b"]),
    ("Summit 24"	, "Summit_001_Zone_024.BP_Interactable_AddItem_C_1"			, materials["parts_lv6_b"]),
    ("Summit 24"	, "Summit_001_Zone_024.BP_Interactable_AddItem_C_2"			, materials["parts_lv6_b"]),
    ("Summit 27"	, "Summit_001_Zone_027.BP_Interactable_AddItem_C_0"			, tips["tip_motleysterminal_01"]),
    ("Summit 28"	, "Summit_001_Zone_028.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Summit 3"		, "Summit_001_Zone_030.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),

    ("Swamp 2"		, "Swamp_001_Zone_002.BP_Breakable_SpawnItem_Box_01_C_1"	, currencies["Default"]),
    ("Swamp 2"		, "Swamp_001_Zone_002.BP_Interactable_AddItem_C_2"			, tips["tip_vials_01"]),
    ("Swamp 2"		, "Swamp_001_Zone_002.BP_Interactable_AddItem_C_3"			, passives["damage_up_targetdebuffed_1"]),
    ("Swamp 4"		, "Swamp_001_Zone_004.EVT_ev_s_e0203_Scarab_Defeat"			, materials["parts_lv4_a"]),
    ("Swamp 6"		, "Swamp_001_Zone_006.BP_Interactable_AddItem_C_1"			, materials["parts_lv3_b"]),
    ("Swamp 6"		, "Swamp_001_Zone_006.BP_Interactable_AddItem_C_2"			, stats["passive_slot_s"]),
    ("Swamp 7"		, "Swamp_001_Zone_007.BP_Interactable_AddItem_C_0"			, tips["tip_lightsilence_01"]),
    ("Swamp 8"		, "Swamp_001_Zone_008.BP_Breakable_SpawnItem_Pod_01_C_1"	, currencies["Default"]),
    ("Swamp 9"		, "Swamp_001_Zone_009.BP_Interactable_AddItem_C_0"			, tips["tip_tornjournal_01"]),
    ("Swamp 1"		, "Swamp_001_Zone_010.BP_Interactable_AddItem_C_1"			, passives["damage_up_skillcategory_auto_1"]),
    ("Swamp 1"		, "Swamp_001_Zone_010.BP_Interactable_TreasureBox_C_1"		, stats["shop_line_up"]),
    ("Swamp 12"		, "Swamp_001_Zone_012.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Swamp 13"		, "Swamp_001_Zone_013.BP_Interactable_AddItem_C_0"			, stats["hp_up_s"]),
    ("Swamp 15"		, "Swamp_001_Zone_015.EVT_ev_s_e6010_Cluster_Defeat"		, aptitudes["Hook"]),
    ("Swamp 18"		, "Swamp_001_Zone_018.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Swamp 19"		, "Swamp_001_Zone_019.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Swamp 2"		, "Swamp_001_Zone_020.BP_Interactable_AddItem_C_1"			, passives["damage_up_targetstunned_1"]),

    ("Tower 1"		, "Tower_001_Zone_001.BP_Breakable_SpawnItem_Pod_01_C_1"	, stats["hp_up_s"]),
    ("Tower 4"		, "Tower_001_Zone_004.BP_Breakable_SpawnItem_Box_01_C_2"	, passives["experience_up_1"]),
    ("Tower 4"		, "Tower_001_Zone_004.BP_Breakable_SpawnItem_Pod_01_C_2"	, stats["passive_slot_s"]),
    ("Tower 6"		, "Tower_001_Zone_006.BP_Interactable_AddItem_C_0"			, currencies["Default"]),
    ("Tower 7"		, "Tower_001_Zone_007.BP_Interactable_AddItem_C_1"			, tips["tip_chieftunerjournal_01"]),
    ("Tower 7"		, "Tower_001_Zone_007.BP_Interactable_AddTutorial_C_1"		, tips["tip_magicrecord_01"]),
    ("Tower 9"		, "Tower_001_Zone_009.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Tower 1"		, "Tower_001_Zone_010.EVT_ev_s_e0162_Gang_Defeat"			, materials["parts_lv2_b"]),
    ("Tower 12"		, "Tower_001_Zone_012.BP_Interactable_AddItem_C_1"			, currencies["Default"]),
    ("Tower 14"		, "Tower_001_Zone_014.BP_Interactable_AddItem_C_1"			, tips["tip_frostgrimoire_01"]),
    ("Tower 14"		, "Tower_001_Zone_014.BP_Interactable_AddItem_C_2"			, currencies["Default"]),
    ("Tower 14"		, "Tower_001_Zone_014.BP_Interactable_TreasureBox_C_1"		, stats["shop_line_up"]),
    ("Tower 14"		, "Tower_001_Zone_014.BP_Interactable_TreasureBox_C_2"		, passives["damage_up_skillcategory_repeat_1"]),
    ("Tower 15"		, "Tower_001_Zone_015.BP_Interactable_AddItem_C_1"			, stats["hp_up_s"]),
    ("Tower 16"		, "Tower_001_Zone_016.EVT_ev_s_e5060_Beast_Defeat"			, spirits["s5060_beast"]),
    ("Tower 18"		, "Tower_001_Zone_018.BP_Interactable_AddItem_C_0"			, tips["tip_homunculusrecord_02"]),
    ("Tower 19"		, "Tower_001_Zone_019.BP_Interactable_TreasureBox_C_1"		, passives["reduce_skill_cooldown_1"]),
]



locations: Dict[str, LocationData] = {location.name: location for location in [
    LocationData("Goal"			, content=events["Victory"]),

    LocationData("Ruins 4 - Nola"			,                           address=1, key="Ruins_001_Zone_004.BP_Trigger_Event_C_0"			,              group=LocationGroup.Event,        content=items["Nola"]),
    LocationData("Ruins 5 - Charmed Fragment"			,               address=2, key="Ruins_001_Zone_005.BP_Interactable_AddItem_C_1"			,       group=LocationGroup.Interactable, content=items["Charmed Fragment"]),
    LocationData("Ruins 12 - Subterranean Testing Site Key"			, address=3, key="Ruins_001_Zone_012.BP_Interactable_AddItem_Skill_C_0"			, group=LocationGroup.Interactable, content=items["Subterranean Testing Site Key"]),
    LocationData("Ruins 12 - Lito"			,                          address=4, key="Ruins_001_Zone_012.BP_BossSpawner_C_0"			,                group=LocationGroup.Boss,         content=items["Lito"]),
    LocationData("Ruins 13 - Homunculus Research Log 1"			,     address=5, key="Ruins_001_Zone_013.BP_Interactable_AddItem_C_1"			,       group=LocationGroup.Interactable, content=items["Homunculus Research Log 1"]),
    LocationData("Ruins 14 - Worn Experiment Log"			,           address=6, key="Ruins_001_Zone_014.BP_Interactable_AddItem_C_1"			,       group=LocationGroup.Interactable, content=items["Worn Experiment Log"]),
    LocationData("Ruins 15 - Healing Ward"			,                  address=7, key="Ruins_001_Zone_015.BP_Trigger_Event_C_0"			,              group=LocationGroup.Event,        content=items["Healing Ward"]),

    LocationData("Ruins 7 - Lever"			,                                                                                                 group=LocationGroup.Event,        content=events["Ruins 7 Lever"]),


    LocationData("Crossroad 2 - Charmed Fragment"			,           address=8, key="Crossroad_001_Zone_002.BP_Interactable_AddItem_C_1"			,  group=LocationGroup.Interactable,  content=items["Charmed Fragment"]),
    LocationData("Crossroad 5 - Aerial Jump"			,                address=9, key="Crossroad_001_Zone_005.BP_Trigger_Event_C_0"			,         group=LocationGroup.Event,         content=items["Aerial Jump"]),
    LocationData("Crossroad 5 - Dodge"			,                      address=10,key="Crossroad_001_Zone_005.BP_Trigger_Event_C_0.1"			,       group=LocationGroup.Event,         content=items["Dodge"]),

    LocationData("Slum 1 - Tattered Letter"			,                 address=11,key="Slum_001_Zone_001.BP_Interactable_AddItem_C_1"			,       group=LocationGroup.Interactable,  content=items["Tattered Letter"]),
    LocationData("Slum 1 - Eye of the Homunculus"			,           address=12,key="Slum_001_Zone_001.BP_Interactable_AddItem_C_2"			,       group=LocationGroup.Interactable,  content=items["Eye of the Homunculus"]),
]}
